### ISSUE TITLE
Port nightly build to github actions

### ISSUE THREAD

**Issue by lazka** [msys2/msys2-installer#9]
We currently use azure-pipelines to build the installer, then update assets for an existing tag on github. I haven't found a github action that allows updating an asset. The official one doesn't support it, see https://github.com/actions/upload-release-asset/issues/13

If anyone has any ideas please tell me :)

**Comment by lazka** [comment]
@eine would https://github.com/eine/tip work here?

**Comment by eine** [comment]
In fact, eine/tip is just a Python script which uses [PyGithub](https://github.com/PyGithub/PyGithub) to interact with GitHub's API. Hence, you can retrieve and execute it, ignoring Docker. You need to provide all the envvars, though: INPUT_FILES, GITHUB_TOKEN|INPUT_TOKEN, GITHUB_REPOSITORY... 

The Action is a "Docker Action" because that's the only alternative provided by GitHub to write non-JS|TS Actions. The solution/workaround to update assets generated in Windows jobs, is to first upload them as artifacts. See, for example: https://github.com/ghdl/ghdl/blob/master/.github/workflows/push.yml#L104-L114.

Anyway, note eine/tip#157.

**Comment by lazka** [comment]
thanks! using eine/tip now
